---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongodb
  namespace: default
  labels:
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/instance: free5gc
secrets:
  - name: mongodb
