apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: tn
  labels:
    app.kubernetes.io/name: tn-operator
  name: tn-leader-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: leader-election-role-tn-operator
subjects:
- kind: ServiceAccount
  name: tn-operator
  namespace: tn
