apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tn-operator-role
rules:
- apiGroups:
  - slice.winlab.nycu
  resources:
  - tnslices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - slice.winlab.nycu
  resources:
  - tnslices/finalizers
  verbs:
  - update
- apiGroups:
  - slice.winlab.nycu
  resources:
  - tnslices/status
  verbs:
  - get
  - patch
  - update
