apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: free5gc-nssf
  labels:
    app.kubernetes.io/name: nssf-document-operator
  name: nssf-document-leader-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: leader-election-role-nssf-document
subjects:
- kind: ServiceAccount
  name: nssf-document-operator
  namespace: free5gc-nssf
