apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: nftopology
  labels:
    app.kubernetes.io/name: nftopology
  name: nftopology-leader-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nftopology-leader-election-role
subjects:
- kind: ServiceAccount
  name: nftopology-operator
  namespace: nftopology
