apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nftopology-role
rules:
- apiGroups:
  - req.winlab.nycu
  resources:
  - nftopologies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - req.winlab.nycu
  resources:
  - nftopologies/finalizers
  verbs:
  - update
- apiGroups:
  - req.winlab.nycu
  resources:
  - nftopologies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - config.porch.kpt.dev
  resources:
  - packagevariants
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - config.porch.kpt.dev
  resources:
  - packagevariants/finalizers
  verbs:
  - update
- apiGroups:
  - config.porch.kpt.dev
  resources:
  - packagevariants/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - config.porch.kpt.dev
  resources:
  - repositories
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - porch.kpt.dev
  resources:
  - packagerevisionresources
  - packagerevisions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
