---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nrf-configmap
  labels:
    app.kubernetes.io/version: "v3.1.1"
    app: free5gc
data:
  nrfcfg.yaml: |
    info:
      version: 1.0.1
      description: NRF initial local configuration
    
    configuration:
      MongoDBName: free5gc
      MongoDBUrl: mongodb://mongodb:27017

      serviceNameList:
        - nnrf-nfm
        - nnrf-disc

      sbi:
        scheme: http
        registerIPv4: nrf-nnrf  # IP used to serve NFs or register to another NRF
        bindingIPv4: 0.0.0.0    # IP used to bind the service
        port: 8000
        tls:
          key: config/TLS/nrf.key
          pem: config/TLS/nrf.pem
      DefaultPlmnId:
        mcc: 208
        mnc: 93

    logger:
      NRF:
        ReportCaller: false
        debugLevel: info
