apiVersion: fn.kpt.dev/v1alpha1
kind: ApplyReplacements
metadata:
  name: propagate-name-sd
  annotations:
    config.kubernetes.io/local-config: "true"
replacements:
- source:
    kind: ConfigMap
    name: slice-info
    fieldPath: data.sd
  targets:
  - select:
      kind: NFDeployment
    fieldPaths:
    - metadata.name
    options:
      delimiter: '-'
      index: 2
  - select:
      kind: Interface
    fieldPaths:
    - metadata.annotations.[specializer.nephio.org/owner]
    options:
      delimiter: '-'
      index: 2
  - select:
      kind: Dependency
    fieldPaths:
    - metadata.annotations.[specializer.nephio.org/owner]
    options:
      delimiter: '-'
      index: 2
  - select:
      kind: NFConfig
    fieldPaths:
    - spec.configRefs.1.spec.PLMNInfo.0.nssai.0.sd