apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: free5gc
  name: free5gc-operator-leader-election-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: free5gc-operator-leader-election-role
subjects:
- kind: ServiceAccount
  name: free5gc-operator
