apiVersion: req.nephio.org/v1alpha1
kind: Interface
metadata:
  name: n3
  annotations:
    nephio.org/network-name: n3
    config.kubernetes.io/local-config: "true"
    specializer.nephio.org/owner: workload.nephio.org/v1alpha1.NFDeployment.upf-1-ffffff
    specializer.nephio.org/namespace: example
spec:
  networkInstance:
    name: n3
  cniType: macvlan
  attachmentType: none
