---
apiVersion: v1
kind: ConfigMap
metadata:
  name: webui-configmap
  labels:
    app.kubernetes.io/version: "v3.1.1"
    app: free5gc
data:
  webuicfg.yaml: |
    info:
      version: 1.0.0
      description: WEBUI initial local configuration

    configuration:
      mongodb:
        name: free5gc
        url: mongodb://mongodb:27017
        
    logger:
      WEBUI:
        ReportCaller: false
        debugLevel: info
