kind: Service
apiVersion: v1
metadata:
  name: tn-manager-svc
spec:
  selector:
    app: tn-manager
  type: NodePort
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
    nodePort: 30188
