apiVersion: req.nephio.org/v1alpha1
kind: Dependency
metadata:
  name: upf
  annotations:
    config.kubernetes.io/local-config: "true"
    specializer.nephio.org/owner: workload.nephio.org/v1alpha1.NFDeployment.smf-1-ffffff
    specializer.nephio.org/namespace: example
spec:
  packageName: upf-1-ffffff
  injectors:
  - apiVersion: workload.nephio.org/v1alpha1
    kind: NFDeployment
    spec:
      provider: upf.free5gc.io